"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import glob
from setuptools import setup

ENTRY_POINT = ['CourtwatchScraper.py']

DATA_FILES = ['index.html', 'LU_scraper.py', 'drive_search.js']
DATA_FILES += [('credentials', glob.glob('credentials/**', recursive=True))]
DATA_FILES += [('static/css', glob.glob('static/css/*', recursive=True))]
DATA_FILES += [('static/fonts', glob.glob('static/fonts/*', recursive=True))]
DATA_FILES += [('static/font-awesome/css', glob.glob('static/font-awesome/css/*', recursive=True))]
DATA_FILES += [('static/font-awesome/fonts', glob.glob('static/font-awesome/fonts/*', recursive=True))]
DATA_FILES += [('static/font-awesome/less', glob.glob('static/font-awesome/less/*', recursive=True))]
DATA_FILES += [('static/font-awesome/scss', glob.glob('static/font-awesome/scss/*', recursive=True))]

OPTIONS = {
    'argv_emulation': False,
    'strip': True,
    #'iconfile': 'staticicon.icns',
    'includes': ['WebKit', 'Foundation', 'webview'],
}

setup(
    app=ENTRY_POINT,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)